# File generated by `generate.py` which uses ts2python.

from enum import Enum, IntEnum
from typing import Union, Optional, Any, Generic, TypeVar, Callable, List, Tuple, Dict, TypedDict, NotRequired, Literal, Iterable, Iterator


AgentClientProtocol = 'ClientRequest | ClientResponse | ClientNotification | AgentRequest | AgentResponse | AgentNotification'

ClientRequest = 'WriteTextFileRequest | ReadTextFileRequest | RequestPermissionRequest'

PermissionOptionKind = Literal["allow_once", "allow_always", "reject_once", "reject_always"]

class ToolCallContent_0(TypedDict):
    content: 'ContentBlock'
    type: Literal["content"]
class ToolCallContent_1(TypedDict):
    newText: str
    oldText: str | None
    path: str
    type: Literal["diff"]
ToolCallContent = ToolCallContent_0 | ToolCallContent_1

class ContentBlock_0(TypedDict):
    annotations: NotRequired['Annotations | None']
    text: str
    type: Literal["text"]
class ContentBlock_1(TypedDict):
    annotations: NotRequired['Annotations | None']
    data: str
    mimeType: str
    type: Literal["image"]
class ContentBlock_2(TypedDict):
    annotations: NotRequired['Annotations | None']
    data: str
    mimeType: str
    type: Literal["audio"]
class ContentBlock_3(TypedDict):
    annotations: NotRequired['Annotations | None']
    description: NotRequired[str | None]
    mimeType: NotRequired[str | None]
    name: str
    size: NotRequired[float | None]
    title: NotRequired[str | None]
    type: Literal["resource_link"]
    uri: str
class ContentBlock_4(TypedDict):
    annotations: NotRequired['Annotations | None']
    resource: 'EmbeddedResourceResource'
    type: Literal["resource"]
ContentBlock = ContentBlock_0 | ContentBlock_1 | ContentBlock_2 | ContentBlock_3 | ContentBlock_4

Role = Literal["assistant", "user"]

EmbeddedResourceResource = Union['TextResourceContents', 'BlobResourceContents']

ToolKind = Literal["read", "edit", "delete", "move", "search", "execute", "think", "fetch", "other"]

ToolCallStatus = Literal["pending", "in_progress", "completed", "failed"]

ClientResponse = 'WriteTextFileResponse | ReadTextFileResponse | RequestPermissionResponse'

WriteTextFileResponse = None

class RequestPermissionOutcome_0(TypedDict):
    outcome: Literal["cancelled"]
class RequestPermissionOutcome_1(TypedDict):
    optionId: str
    outcome: Literal["selected"]
RequestPermissionOutcome = RequestPermissionOutcome_0 | RequestPermissionOutcome_1

ClientNotification = 'CancelNotification'

AgentRequest = 'InitializeRequest | AuthenticateRequest | NewSessionRequest | LoadSessionRequest | PromptRequest'

AgentResponse = 'InitializeResponse | AuthenticateResponse | NewSessionResponse | LoadSessionResponse | PromptResponse'

AuthenticateResponse = None

LoadSessionResponse = None

PromptResponse = None

AgentNotification = 'SessionNotification'

class SessionUpdate_0(TypedDict):
    content: ContentBlock
    sessionUpdate: Literal["user_message_chunk"]
class SessionUpdate_1(TypedDict):
    content: ContentBlock
    sessionUpdate: Literal["agent_message_chunk"]
class SessionUpdate_2(TypedDict):
    content: ContentBlock
    sessionUpdate: Literal["agent_thought_chunk"]
class SessionUpdate_3(TypedDict):
    content: NotRequired[List[ToolCallContent]]
    kind: ToolKind
    locations: NotRequired[List['ToolCallLocation']]
    rawInput: NotRequired[Any]
    sessionUpdate: Literal["tool_call"]
    status: ToolCallStatus
    title: str
    toolCallId: str
class SessionUpdate_4(TypedDict):
    content: NotRequired[List[ToolCallContent] | None]
    kind: NotRequired[ToolKind | None]
    locations: NotRequired[List['ToolCallLocation'] | None]
    rawInput: NotRequired[Any]
    sessionUpdate: Literal["tool_call_update"]
    status: NotRequired[ToolCallStatus | None]
    title: NotRequired[str | None]
    toolCallId: str
class SessionUpdate_5(TypedDict):
    entries: List['PlanEntry']
    sessionUpdate: Literal["plan"]
SessionUpdate = SessionUpdate_0 | SessionUpdate_1 | SessionUpdate_2 | SessionUpdate_3 | SessionUpdate_4 | SessionUpdate_5


class WriteTextFileRequest(TypedDict):
    content: str
    path: str
    sessionId: str


class ReadTextFileRequest(TypedDict):
    limit: NotRequired[float | None]
    line: NotRequired[float | None]
    path: str
    sessionId: str


class RequestPermissionRequest(TypedDict):
    options: List['PermissionOption']
    sessionId: str
    toolCall: 'ToolCall'


class PermissionOption(TypedDict):
    kind: PermissionOptionKind
    name: str
    optionId: str


class ToolCall(TypedDict):
    content: NotRequired[List[ToolCallContent]]
    kind: ToolKind
    locations: NotRequired[List['ToolCallLocation']]
    rawInput: NotRequired[Any]
    status: ToolCallStatus
    title: str
    toolCallId: str


class Annotations(TypedDict):
    audience: NotRequired[List[Role] | None]
    lastModified: NotRequired[str | None]
    priority: NotRequired[float | None]


class TextResourceContents(TypedDict):
    mimeType: NotRequired[str | None]
    text: str
    uri: str


class BlobResourceContents(TypedDict):
    blob: str
    mimeType: NotRequired[str | None]
    uri: str


class ToolCallLocation(TypedDict):
    line: NotRequired[float | None]
    path: str


class ReadTextFileResponse(TypedDict):
    content: str


class RequestPermissionResponse(TypedDict):
    outcome: RequestPermissionOutcome


class CancelNotification(TypedDict):
    sessionId: str


class InitializeRequest(TypedDict):
    clientCapabilities: 'ClientCapabilities'
    protocolVersion: float


class ClientCapabilities(TypedDict):
    fs: 'FileSystemCapability'


class FileSystemCapability(TypedDict):
    readTextFile: bool
    writeTextFile: bool


class AuthenticateRequest(TypedDict):
    methodId: str


class NewSessionRequest(TypedDict):
    cwd: str
    mcpServers: List['McpServer']


class McpServer(TypedDict):
    args: List[str]
    command: str
    env: List['EnvVariable']
    name: str


class EnvVariable(TypedDict):
    name: str
    value: str


class LoadSessionRequest(TypedDict):
    cwd: str
    mcpServers: List[McpServer]
    sessionId: str


class PromptRequest(TypedDict):
    prompt: List[ContentBlock]
    sessionId: str


class InitializeResponse(TypedDict):
    agentCapabilities: 'AgentCapabilities'
    authMethods: List['AuthMethod']
    protocolVersion: float


class AgentCapabilities(TypedDict):
    loadSession: bool


class AuthMethod(TypedDict):
    description: str | None
    id: str
    name: str


class NewSessionResponse(TypedDict):
    sessionId: str


class SessionNotification(TypedDict):
    sessionId: str
    update: SessionUpdate


class PlanEntry(TypedDict):
    content: str
    priority: Literal["high", "medium", "low"]
    status: Literal["pending", "in_progress", "completed"]